### PR TITLE
#22 added search box

### PR DESCRIPTION
**Pull request by VictoriaAjala**

### CODE REVIEW

**Comment by OladapoAjala** [comment]
Hi @VictoriaAjala please attach an image showing your changes thanks

**Comment by VictoriaAjala** [comment]
> Hi @VictoriaAjala please attach an image showing your changes thanks

Still working on this

**Comment by VictoriaAjala** [comment]
@OladapoAjala  I've fixed this please merge #22

**Comment by OladapoAjala** [comment]
@VictoriaAjala please attach screenshots of the frontend

**Comment by VictoriaAjala** [comment]
Screenshot 2022-08-19 at 14-55-22 Weather app
@OladapoAjala

**Comment by OladapoAjala** [comment]
LGTM

**Review by OladapoAjala — APPROVED** [review]

**Pull request merged**
